Добавляет разметку страницы index.html и meta-информацию
htmlacademy-htmlcss/1826607-sedona-33 pull request #2
Opened 2022-01-21 18:06 UTC by andreevvaleksandr

2022-01-22 15:06 UTC, GennadiyM requested changes

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +        <img class="page-header-logo" src="" alt="Логотип Седоны">
width, height

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +      <a class="navigation-logo" href="#">
href="index.html" но вообще про это места я на созвоне чуть больше расскажу

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +        <img class="page-header-logo" src="" alt="Логотип Седоны">
атрибуты width, height

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <a class="navigation-link navigation-link-current" href="#">Главная</a>
index.html

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <a class="navigation-link" href="#">О Седоне</a>
советую все href="#" замемить на href="#nowhere" - тогда не будет дергаться страница при нажати на такую ссылку

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +            <span class="visually-hidden">Искать по гостиницам</span>
для облегчения верстки такие скрытые текста можно поместить в атрибут aria-label у ссылки

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +            <span class="visually-hidden">Забронировать гостиницу</span>
я может куда то не туда смотрю, но я не нешал в макете в шапке такой ссылки. Там есть хочу сюда.

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <a class="navigation-link" href="#">
class="navigation-favorite"

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +            <span class="visually-hidden">Искать по гостиницам</span>
class="navigation-search"

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +            <span class="visually-hidden">Перейти в избранное</span>
<span class="navigation-favorite-count">12</span>

2022-01-22 15:06 UTC, GennadiyM commented on style.css
> +    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
ну зная, что ты дизайнер, я думаю ты тут подобрал крутую подборку шрифтов, но для этого проекта это перебор. достаточно основного шрифта и одного веб безопасного. font-family: "Roboto", "Open Sans", sans-serif. (и обрати внимание что я проставил их в кавычках) А так же еще не было задания делать css - не беги вперед паровоза

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <a class="btn-flat" href="https://www.youtube.com/c/HTMLAcademyRUS" target="blank">
_blank

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <a class="btn-flat" href="https://www.facebook.com/htmlacademy" target="blank">
_blank

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <a class="btn-flat" href="https://twitter.com/htmlacademy_ru" target="blank">
_blank

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +        <p class="subscription-form-email">
давай p на div заменим. Так будет удобнее. Я видел, что в демках используют p. Поверь моему опыту

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +        <p class="subscription-form-send">
лишний блок

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <input class="btn btn-secondary" type="submit" value="Подписаться"></input>
button type submit, не input

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <span>— №5 —</span>
p

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <span>— №2 —</span>
параграф

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <span>— №3 —</span>
параграф

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <span>— №4 —</span>
параграф

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +    </section>
не тянет на секцию - обычный div

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +      <h2 class="about-title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
не тянет на заголовок. Больше какой-то лозунг. p или b или strong. Тег <strong> указывает на важность отмеченного текста.  я бы использовал его

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +    </section>
здесь убрать закрытие секции

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +    <section class="advantages">
здесь убрать открытие секции

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +    <section class="advantages">
http://joxi.ru/5mdRqLKcax7gDA вот это все одна большая секция

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <input type="email" name="subscription-email" placeholder="Ваш e-mail">
инпут оберни в label

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <input class="btn btn-secondary" type="submit" value="Подписаться"></input>
и вот эту кнопку положи в див, который оборачивает поле email

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +      <p class="subscription description">Только полезная информация и никакого спама, честное бойскаутское!</p>
кажется дефис пропустил

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +      <button class="btn btn-primary" role="button">Поиск гостиницы в Седоне</button>
сделай лучше ссылкой. Потом расскажу зачем

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +      <button class="btn btn-primary" role="button">Поиск гостиницы в Седоне</button>
и если делаешь кнопку у нее атрибут type, а не role

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <img src="" alt="">
удали, это будет не контентное изображение

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <img src="" alt="">
удали, это будет не контентное изображение

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <img src="" alt="">
удали, это будет не контентное изображение

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +          <img class="advantages-img" src="" alt="Вид на Седону из гостиницы">
width height

2022-01-22 15:06 UTC, GennadiyM commented on index.html
> +      <img class="welcome-img-text" src="" alt="Добро пожаловать в великолепный городок Седону!">
тут только одна контентая картинка - это welocome. И width и height допиши

2022-01-22 15:10 UTC, GennadiyM requested changes

2022-01-22 15:10 UTC, GennadiyM commented on index.html
> +    </section>
лучше div

2022-01-22 15:10 UTC, GennadiyM commented on index.html
> +      <h2 class="visually-hidden">Логотип</h2>
соответсвенно это убрать

2022-01-22 15:10 UTC, GennadiyM commented on index.html
> +      <img class="footer-logo" src="" alt="Логотип HTML Academy">
а картинку обернуть в ссылку (а в будущем мы тут и картинку заменим)

2022-01-22 15:10 UTC, GennadiyM commented on index.html
> +    </section>
просто ссылка на телефон,  убери секцию и h2

2022-01-24 13:53 UTC, andreev-alex commented on index.html
> +          <span>— №2 —</span>
вместо span или заголовка h3?

2022-01-24 13:53 UTC, andreevvaleksandr commented on index.html
> +            <span class="visually-hidden">Забронировать гостиницу</span>
Да, но в этом конкретном кейсе, насколько я понимаю, ссылка ведёт на функционал бронирования гостиницы (поиск в модальном окне). На встрече по разметке ведущие говорили, что стоит указывать на конкретный функционал. Что думаешь, - переименовать на _Хочу сюда_ или оставляем _Забронировать гостиницу_  ?

2022-01-25 14:37 UTC, GennadiyM requested changes

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <ul class="navigation-list navigation-user">
там другие отсупы и некоторые вещи явно отличаются от navigation-list. оставь только navigation-user.  И назови правильно user-navigation.

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        </li>
соответственно тут все под именную группу user-navigation подвести надо.

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <h2 class="visually-hidden">Почему Седона круче Гранд-Каньон?</h2>
не заголовок.  Заголовк должен быть емким, кратким, без воды. А это какой-то вопрос подводящий к теме. Описание города Седона или что то вроде этого и заг h1 уровня . Я бы назвал просто Город седона. ну на крайний случай Визитка города Седона.

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <h1 class="visually-hidden">Седона — добро пожаловать в великолепный городок в Аризоне!</h1>
убери это

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +          <h3 class="advantages-title">Настоящий городок</h3>
все и ниже идущие заголовки понизить до уровня h2

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        </li>
Убрать

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +          <img class="advantages-img" src="" width="800px" height="384px" alt="Вид на Седону из гостиницы">
мы не пишем px в аптрибутах width и height - а это говорит мне о том что ты не проверил на валидность код

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +          <p class="advantages-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
div class="advantages-img">
      img  src="" width="800" height="384" alt="Вид на Седону из гостиницы">
 /div>

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        </li>
http://joxi.ru/5mdRqLKcq4KRWA это один целый блок

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        <li class="advantages-item">
class="advantages-item big-item

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        <li class="advantages-item">
и соответственно внутр http://joxi.ru/5mdRqLKcq4KRWA  этого блока все имена классов содержат в себе big-item

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        </li>
не забыть про эту картинку и не забыть про пиксели

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        <li class="advantages-item">
class="advantages-item big-item big-item-revert" при помощи big-item-revert мы перевернем местами текст и картинку

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        </li>
li class="advantages-item small-item small-item-цветовое обозначение карточки (small-item-blue, small-item-light-blue) и один цвет по умолчанию. Сделаешь как тебе удобнее

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <a class="btn btn-primary">Поиск гостиницы в Седоне</a>
href="form.html" если у нас сломается кнопка мы переотправим пользователя на старницу с формой как в попапе

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        <div class="subscription-form-email">
class="subscription-content"

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +          <label>
class="subscription-email"

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +          <button class="btn btn-secondary" type="submit">Подписаться</button>
class="subscription-email btn btn-secondary". при помощи subscription-email  мы ее будем задавать ее положение внутри обертки

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +    <div class="footer-social">
вот тут или оставляй section или удаляй этот див и нижестоящий заголовок (лучше удаляй, редко кто так делает, ни разу на продакшене такого не видел)

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <ul class="footer-social-list">
и соответственно после того как удалишь можешь делать class="footer-social social" в footer-social  будешь задавать что-то связанно с положением этого блока в футере, или удалишь если такие манипуляции не потребуются. в social будешь писать основные стили блока. Соответственно все классы ниже надо переименовать

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <img class="fnavigation-logo" src="" alt="Логотип HTML Academy">
убери тут img мы по другому втсавим ее тут

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +    <a class="footer-logo" href="index.html">
а вот здесь aria-label = ссылка на html academy"

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +          <a class="btn-flat" href="https://twitter.com/htmlacademy_ru" target="_blank">
ну раз в других местах aria-label, то почему бы и тут не воспользоваться данной логикой

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +        <img class="page-header-logo" src="" width="139px" height="70px" alt="Логотип Седоны">
пиксели

2022-01-25 14:37 UTC, GennadiyM commented on index.html
> +      <img class="welcome-img" src="" width="1200px" height="485px" alt="Вид на Седону с Гранд-Каньон">
пиксели

2022-01-25 14:47 UTC, andreevvaleksandr commented on index.html
> +          <img class="advantages-img" src="" width="800px" height="384px" alt="Вид на Седону из гостиницы">
Тут ты ошибаешься - на валидность проверяю перед каждым реквестор. Но не всегда понимаю суть ошибок пока что, поэтому решил оставить до твоих комментариев

2022-01-25 19:38 UTC, andreevvaleksandr commented on index.html
> +        <li class="advantages-item">
Может просто в HTML сразу поменять?

2022-01-25 19:49 UTC, andreevvaleksandr commented on index.html
> +          <a class="btn-flat" href="https://twitter.com/htmlacademy_ru" target="_blank">
Вот с этим комментарием не понимаю - смотри, что пишут (у нас ведь есть видимый элемент - текста ссылок): 
[https://developer.mozilla.org/ru/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute](url)

2022-01-26 08:34 UTC, GennadiyM requested changes

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +          <a class="navigation-search" href="#nowhere" arial-label="Искать по гостиницам"></a>
user-navigation-search и дургие блоки по анлагии. если блок чей-то явный ребенок - образование нейминга наследуется от родительского блока

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +    <img class="welcome-img" src="" width="1200" height="485" alt="Вид на Седону с Гранд-Каньон">
ебрни эту картинку в div

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +      <h1 class="slogan">Седона — небольшой городок в Аризоне, заслуживающий большего!</h1>
strong class="slogan">Седона — небольшой городок в Аризоне, заслуживающий большего! strong

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +    <section class="advantages">
h2 visually-hidden  преимущества Седоны

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +  <main class="main-index">
h1 visually-hidden - Седона - город Аризоне

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +      </ul>
классы на лекции перепишем

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +      <h2 class="visually-hidden">Подписаться на рассылку</h2>
подписка на рассылку.

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +        <div class="subscription-email">
я вроде другие классы тут предлагал

2022-01-26 08:34 UTC, GennadiyM commented on index.html
> +            <span class="visually-hidden">Twitter</span>
перенеси в aria-label

2022-01-30 17:38 UTC, merged