Добавляет оптимизированную графику и ссылки на контентные изображения в разметке
htmlacademy-htmlcss/1826607-sedona-33 pull request #3
Opened 2022-01-31 11:40 UTC by andreevvaleksandr

2022-02-02 20:00 UTC, GennadiyM requested changes

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
> +          <li class="arrow-right"></li>
удали стрелочку - это декративная штука сделанная в css

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
>              <a class="breadcrumbs-link" href="catalog.html" aria-label="Гостиницы"></a>
а зачем оно в ариа атрибуте a class="breadcrumbs-link" href="catalog.html">Гостиницы</a

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
> +      <select class="select-control" aria-label="Сортировка" name="sort-search">
Селект крайне сложно стилизуется, сделай див и положи в него ссылку a href="#cheeap" сначала дешевые

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
>      <section class="search-sort-wrapper">
это див с сортировкой, не секция

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
>              <h3 class="hotel-card-title">Amara Resort & Spa</h3>
убери из этой ссылки заголовок и оберни его в собственную ссылку

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
> +            <img class="hotel-card-img" src="images/hotels/hotel-1.jpg" width="299" height="206"
давать класс картинке - излишне. ты даешь класс обертке картинки - в данном случае ссылке

2022-02-02 20:00 UTC, GennadiyM commented on catalog.html
>              <button class="btn btn-flat">Рейтинг: <span class="rate-count">8,5</span></button>
а с чего вдруг это кнопка? что бы она меняла? рейтинг? а как? на 0.00009 или на 10 баллов? А в стайлгайде оно есть? А ты видел где то такое? - обычный параграф

2022-02-05 09:18 UTC, andreevvaleksandr commented on catalog.html
>              <a class="breadcrumbs-link" href="catalog.html" aria-label="Гостиницы"></a>
На лекции говорили, что нужно указать наименование ссылки для доступности, в случае, если нет явного названия элемента (как в этом кейсе)

2022-02-05 09:28 UTC, andreevvaleksandr commented on catalog.html
>              <h3 class="hotel-card-title">Amara Resort & Spa</h3>
Сделал, но валидатор ругает на такое решение (вложение интерактивных элементов друг в друга - ссылка внутри ссылки)

2022-02-06 12:58 UTC, merged