Добавляет flexbox-сетки для крупных блоков
htmlacademy-htmlcss/1826607-sedona-33 pull request #4
Opened 2022-02-13 18:35 UTC by andreevvaleksandr

2022-02-21 22:43 UTC, GennadiyM requested changes

2022-02-21 22:43 UTC, GennadiyM commented on catalog.html
> +        <button class="btn">Загрузить ещё</button>
а где тип кнопки?

2022-02-21 22:43 UTC, GennadiyM commented on catalog.html
> +          <li class="pagination-item pagination-item-disabled">
почему ли отключена, а не ссылка? ссылка интерактивный элемент, ли всего лишь контейнер для нее

2022-02-21 22:43 UTC, GennadiyM commented on catalog.html
> +              <a class="hotel-card-title">Desert Quail Inn</a>
внутрь ссылки положи еще заголовок соблюдая иерархию загловков

2022-02-21 22:43 UTC, GennadiyM commented on catalog.html
> +              <a class="hotel-card-title">GreenTree Inn</a>
href, загловок

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +}
Не по критерию. нельзя fieldset задавать глобальные стили

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +.user-navigation .btn-brown {
а нужен ли тут двойной селектор? просто .btn-grow не подойдет?

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +.breadcrumbs {
а если ссылок будет много (допустим у сайта будет 10 вложенных друг за другом старниц? они так и будут расти на всю длину страницы и не будут переноситься? задать ширину и предусмотреть перенос. Советую воспользоваться grid моделью

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +  margin-right: 11px;
при переходе на грид это нужно будет убрать

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +.catalog-form-wrapper .breadcrumbs {
зачем опять такой селектор?

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +  transition: border 150ms ease-in-out;
0.2s easy

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +  border: 2px solid #E6E6E6;
почему цвет не в переменной

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +  height: 384px;
min-height

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +  transition: all 150ms ease-in-out;
пользоваться all дурной тон, обычно перечисляем те свойства что будут меняться. но можешь оставить

2022-02-21 22:43 UTC, GennadiyM commented on css/styles.css
> +}
тоже лучше на гридах сделать

2022-02-26 17:11 UTC, GennadiyM commented on catalog.html
> +                <h2>Amara Resort & Spa
не закрыл тег

2022-02-26 17:11 UTC, GennadiyM commented on catalog.html
> +                <p class="hotel-rate"></p>
проставить модификаторы class p class="hotel-rate hotel-rate-количество звезд

2022-02-26 17:11 UTC, GennadiyM commented on catalog.html
> +        <li class="footer-social-item twitter">
зачем вот эти модификаторы twitter facebook youtube. Это разные иконки, разность этих иконок ты задаешь тем, что встраиваешь разные svg файлы

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  height: auto;
object-fit и height приведут плюс минус к одному эффекту. Проверим на лекции и удалим ненужное

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  font-family: "PT Sans", Arial, Helvetica, sans-serif;
Arial Helvetica обернуть в кавычки

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  padding: 0;
Почему не учитываешь переполнение списка меню?

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  padding: 20px;
и как применились паддинги? так как ты ожидал? Это строчный элемент. Паддинги у строчныйх и блочных элементов применяются по разному. Задай ссылке display: block

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  list-style: none;
Хорошо, есть максимальная ширина (хотя можно и обычную задать) но опять не учитывается переполнение контейнера (flex-wrap: wrap)

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +.user-navigation .btn-brown {
Ничего не изменилось или не написал ответ

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  /* padding: 30px 72px 80px 72px; */
???

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  width: 248px;
проверить на лекции

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  width: 248px;
пометка для меня, не вижу смысла задавать ширину но могу ошибаться

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  margin-top: 0;
почему только верхний маргин переопределил? нижний маргин, который идет по умолчанию, что имеет макетные значения?

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  margin-bottom: 29px;
почуме только нижний маргин переопределен?

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  margin-bottom: 56px;
так же. Это параграм у него есть маргины по умолчанию. Переопределяешь только один

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  height: 411px;
min-height. Я рассказывал тебе в каких случаях мы можем запретить блоку быть больше каких-то размеров по высоте. А так в этом блоке и min height не нужна

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  height: 411px;
ты добьешься нужной высоту внутрненними паддингами и отступами между внутренними элементами

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  height: 60px;
опять высоту жестко ограничиваешь - в общем выношу в разбор на лекции

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  display: block;
да он вроде у тебя и так как параграф сделан - а p у нас по умолчанию блочный. - проверка на лекции

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  padding: 0;
ну раз ты отсавляешь флекс то не учитываешь переполнение пагинации

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  transition: background-color 0.2s ease;
ох и намешал всего, флекс модель ей не нужна. от ширины и выосты можно отказаться. все делается нужными паддингами и text-align center - разбор на лекции

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  user-select: none;
ну и еще того с pointer events надо поигарть

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +}
не отпозиционированы внутри блока - пока не критично

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +  padding: 0;
не учитывает переполнения

2022-02-26 17:11 UTC, GennadiyM commented on css/styles.css
> +}
а вот будет 5 ссылок и все поедет. я вроде тебе показывал

2022-02-26 17:11 UTC, merged

2022-02-26 18:05 UTC, andreev-alex commented on css/styles.css
> +  margin-bottom: 29px;
Там установил на блок padding 91 и 93px по вертикали